package com.example.accounts.entity.enums;

public enum DimensionType {
    ITEM,
    WAREHOUSE,
    FIXED_ASSET,
    EMPLOYEE,
    TAX_TYPE,
    COMPANY,
    CONTRACT,
    BUSINESS_ACTIVITY,
    BASIS,
    TYPES_OF_PAYMENTS,
    DEFERRED_EXPENSE,
    COST_OBJECT,
    INVESTMENT_PROPERTY,
    CASH_FLOW_ITEM,
    INPUT_VAT_TYPES,
    EXPENSE_ITEM,
    BANK_ACCOUNT,
    CASH_EQUIVALENT,
    PREPAYMENTS_DOCUMENT,
    INCOME_ITEM,
    EQUITY_MOVEMENTS_ITEMS,
    DEFERRED_REVENUE
}
